"""Central path registry for the entire pipeline.

Every pipeline script resolves paths through this module — the repo has exactly
ONE root anchor. Standard header for any script under pipeline/<stage>/:

    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "lib"))
    from paths import REPO_ROOT, CLEAN, ...

R scripts carry an identical inline `find_root()` block (WIA_ROOT env
override, else walk up to pyproject.toml) — inlined because an R script
cannot source a shared helper before knowing the root.
"""

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]  # pipeline/lib/paths.py -> repo root

# ---- committed trees -------------------------------------------------------
RAW = REPO_ROOT / "raw_data"
INPUTS = REPO_ROOT / "inputs"
OUTPUT = REPO_ROOT / "output"          # cleaned waiver CSVs
RESULTS = REPO_ROOT / "results"

# ---- gitignored regenerables (all live under data/) ------------------------
DATA = REPO_ROOT / "data"
CLEAN = DATA / "clean"                 # cleaned parquets
PANELS = DATA / "panels"               # event panel + combined bidlink panel
ANCHORED = DATA / "anchored"           # per-treated anchored panels + matching covariates
DONOR_POOLS = DATA / "donor_pools"     # synth donor pools (per treated x outcome)
CACHE = DATA / "cache"                 # joblib TWFE fit cache (per variant subdir)

# ---- canonical raw inputs --------------------------------------------------
RAW_PROCUREMENT = RAW / "procurement"
RAW_API_BACKFILL = RAW_PROCUREMENT / "api_backfill"
RAW_DLA_FOIA = RAW / "DLA_FOIA"
RAW_BIDLINK = RAW / "bidlink"
RAW_WAIVERS = RAW / "procurement-waivers.csv"

# ---- committed inputs (inputs/) --------------------------------------------
UNIT_COST_CLIN_TAGGING = INPUTS / "unit_cost_clin_tagging.csv"   # manual, read-only
NSN_REFERENCE = INPUTS / "nsn_reference"                          # waiver reference CSVs

# ---- cleaned data products (stage 01) ---------------------------------------
# (dla_foia.py additionally writes contract/procurement history + enriched_base
#  parquets under CLEAN; only enriched_latest is consumed downstream.)
PROCUREMENT_PARQUET = CLEAN / "procurement_data.parquet"
DLA_ENRICHED_LATEST = CLEAN / "dla_contract_enriched_latest.parquet"
BIDLINK_NSN_CSV = CLEAN / "bidlink_nsn.csv"
WAIVERS_CLEANED = OUTPUT / "procurement-waivers-cleaned.csv"     # canonical waiver CSV

# ---- stage products ----------------------------------------------------------
TREATMENT_DATES = RESULTS / "treatment" / "treatment_nsn_first_waiver_dates.csv"
# Regenerated by the `combined_panel` stage (pipeline/03_panels/
# build_combined_bidlink.py) from the archived raw data, after treatment_id
# (it consumes the treatment first-waiver dates). Lives under the gitignored
# data/ tree like the other panels.
COMBINED_BIDLINK_PANEL = PANELS / "combined_bidlink_panel.parquet"
PANEL_ENRICHED = PANELS / "panel_enriched.parquet"
PANEL_DLA_ONLY = PANELS / "panel_dla_only.parquet"


# Thesis-facing artifacts (figures/tables/stats for the manuscript + appendix)
DESCRIPTIVES = RESULTS / "descriptives"
DESCRIPTIVES_FIGURES = DESCRIPTIVES / "figures"
DESCRIPTIVES_TABLES = DESCRIPTIVES / "tables"
DESCRIPTIVES_STATS = DESCRIPTIVES / "stats"
APPENDIX = RESULTS / "appendix"


def variant_suffix(variant: str) -> str:
    """The filename-suffix rule: main is unsuffixed, every other variant is
    `_<variant>`. Single owner of the rule (mirrored in pipeline/lib/paths.R
    for the R scripts, which cannot import this module)."""
    return "" if variant == "main" else f"_{variant}"


def results_root(variant: str = "main") -> Path:
    """Committed results tree for a variant (main, dla_only, uniform_sample, non_container)."""
    return RESULTS / variant


# ---- results-layout functions (single owner; pipeline/lib/paths.R mirrors
# ---- these for the R scripts) ------------------------------------------------
def panel_logs(variant: str = "main") -> Path:
    return results_root(variant) / "panels"


def event_study_tables(variant: str = "main") -> Path:
    return results_root(variant) / "event_study" / "tables"


def event_study_figures(variant: str = "main") -> Path:
    return results_root(variant) / "event_study" / "figures"


def event_study_json(variant: str) -> Path:
    return results_root(variant) / "event_study" / "event_study.json"


def matched_tables(variant: str = "main") -> Path:
    return results_root(variant) / "matched" / "tables"


def matched_logs(variant: str = "main") -> Path:
    return results_root(variant) / "matched" / "logs"


def synth_tables(variant: str = "main") -> Path:
    return results_root(variant) / "synth" / "tables"


def synth_figures(variant: str = "main") -> Path:
    return results_root(variant) / "synth" / "figures"


def synth_logs(variant: str = "main") -> Path:
    return results_root(variant) / "synth" / "logs"


def anchored_panel_path(variant: str = "main") -> Path:
    """Anchored panel parquet for a panel variant. Filenames preserved from the
    original pipeline (anchored_panel.parquet / anchored_panel_dla_only.parquet)."""
    return ANCHORED / f"anchored_panel{variant_suffix(variant)}.parquet"


def donor_universe_path(variant: str = "main") -> Path:
    """Donor universe CSV, rebuilt each run by build_donor_universe.py."""
    return DATA / f"donor_universe{variant_suffix(variant)}.csv"


def cache_dir(variant: str = "main") -> Path:
    return CACHE / variant
