"""Build the combined treatment + control BidLink transaction panel.

The `combined_panel` stage (runs after treatment_id, before event_panel). Stacks
the treatment + control BidLink line items and enriches them against FPDS. One
row = one BidLink line item (NSN, Contract, Order, Line, Date). FPDS enrichment
is filtered to original awards only (modification_number = "0"), so there is no
row multiplication.

The combined panel is regenerated by the combined_panel stage from the archived inputs.

Inputs:
  - data/clean/bidlink_nsn.csv (treatment BidLink)
  - raw_data/bidlink/control_contracts/*.csv (63 control BidLink files)
  - data/clean/procurement_data.parquet (FPDS)
  - results/treatment/treatment_nsn_first_waiver_dates.csv
  - data/clean/dla_contract_enriched_latest.parquet (canonical control NSNs)

Output:
  - data/panels/combined_bidlink_panel.parquet

Usage (normally run via reproduce.py --only combined_panel):
  uv run python pipeline/03_panels/build_combined_bidlink.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import polars as pl

# --- Make lib + sibling loaders importable ---
_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent / "lib"))

from bidlink_core import (
    collect_candidate_piids,
    compute_join_piid,
    enrich_with_fpds,
    enrich_unmatched_via_parent,
    load_fpds_for_piids,
)
from load_treatment_bidlink import load_treatment_bidlink
from load_control_bidlink import load_control_bidlink
from paths import COMBINED_BIDLINK_PANEL, PROCUREMENT_PARQUET, REPO_ROOT

OUT_PARQUET = COMBINED_BIDLINK_PANEL  # data/panels/combined_bidlink_panel.parquet

pl.Config.set_tbl_formatting("ASCII_MARKDOWN")
pl.Config.set_tbl_rows(40)
pl.Config.set_tbl_cols(16)

PARQUET_PATH = PROCUREMENT_PARQUET


def main() -> None:
    # ==================================================================
    # Step 1: Load both sides
    # ==================================================================
    print("=" * 70)
    print("STEP 1: Load BidLink data")
    print("=" * 70)

    treatment = load_treatment_bidlink()
    print(f"Treatment: {treatment.height} rows, {treatment['bl_nsn'].n_unique()} NSNs")

    control = load_control_bidlink()
    print(f"Control:   {control.height} rows, {control['bl_nsn'].n_unique()} NSNs")

    # ==================================================================
    # Step 2: Stack
    # ==================================================================
    print("\n" + "=" * 70)
    print("STEP 2: Combine treatment + control")
    print("=" * 70)

    combined = pl.concat([treatment, control], how="diagonal")
    print(f"Combined: {combined.height} rows")
    print(f"  Treatment: {combined.filter(pl.col('role') == 'treatment').height}")
    print(f"  Control:   {combined.filter(pl.col('role') == 'control').height}")
    print(f"  Unique NSNs: {combined['bl_nsn'].n_unique()}")

    # ==================================================================
    # Step 3: FPDS enrichment (one parquet scan)
    # ==================================================================
    print("\n" + "=" * 70)
    print("STEP 3: FPDS enrichment")
    print("=" * 70)

    # Collect all candidate PIIDs from both treatment and control
    candidate_piids = collect_candidate_piids(combined)
    print(f"Candidate PIIDs for FPDS scan: {len(candidate_piids)}")

    # Load FPDS (mod 0 only)
    fpds = load_fpds_for_piids(PARQUET_PATH, candidate_piids)
    fpds_piid_set = set(fpds["award_id_piid"].to_list())
    print(f"FPDS rows loaded (mod 0): {fpds.height}")
    print(f"FPDS unique PIIDs: {len(fpds_piid_set)}")

    # Compute join PIID with Order-field fallback
    combined = compute_join_piid(combined, fpds_piid_set)
    n_fallback = combined["used_order_fallback"].sum()
    print(f"Rows using Order fallback: {n_fallback}")

    # Left join to FPDS (primary: join_piid = award_id_piid)
    combined = enrich_with_fpds(combined, fpds)

    n_matched_pass1 = combined.filter(pl.col("matched_to_parquet")).height
    n_unmatched_pass1 = combined.filter(~pl.col("matched_to_parquet")).height
    print(f"Pass 1 (primary join): {n_matched_pass1} matched, {n_unmatched_pass1} unmatched")

    # Second pass: Method D — BPA call orders with short Order codes
    # Join on (bl_order = award_id_piid, bl_contract = parent_award_id_piid)
    combined = enrich_unmatched_via_parent(combined, fpds)

    n_matched_pass2 = combined.filter(pl.col("matched_to_parquet")).height
    n_recovered = n_matched_pass2 - n_matched_pass1
    print(f"Pass 2 (Method D parent join): recovered {n_recovered} additional matches")
    print(f"Final: {n_matched_pass2} matched, {combined.height - n_matched_pass2} unmatched")

    # ==================================================================
    # Step 4: Summary stats
    # ==================================================================
    print("\n" + "=" * 70)
    print("STEP 4: Summary")
    print("=" * 70)

    print(f"\nFinal panel: {combined.height} rows, {combined.width} columns")

    # Match rates by role
    for role in ["treatment", "control"]:
        subset = combined.filter(pl.col("role") == role)
        n_matched = subset.filter(pl.col("matched_to_parquet")).height
        n_total = subset.height
        pct = n_matched / n_total * 100 if n_total > 0 else 0
        n_nsns = subset["bl_nsn"].n_unique()
        print(f"  {role:10s}: {n_total} rows, {n_nsns} NSNs, "
              f"FPDS match: {n_matched}/{n_total} ({pct:.1f}%)")

    # Order fallback breakdown
    fallback_by_role = (
        combined.group_by("role")
        .agg(
            pl.col("used_order_fallback").sum().alias("n_fallback"),
            pl.len().alias("n_total"),
        )
    )
    print(f"\nOrder fallback usage:")
    print(fallback_by_role)

    # FY coverage
    print(f"\nFY range:")
    for role in ["treatment", "control"]:
        subset = combined.filter(pl.col("role") == role)
        fy_min = subset["bl_fiscal_year"].min()
        fy_max = subset["bl_fiscal_year"].max()
        print(f"  {role:10s}: FY{fy_min}-FY{fy_max}")

    # ==================================================================
    # Step 5: Export
    # ==================================================================
    print("\n" + "=" * 70)
    print("STEP 5: Export")
    print("=" * 70)

    out_parquet = OUT_PARQUET
    out_parquet.parent.mkdir(parents=True, exist_ok=True)

    combined.write_parquet(out_parquet)
    print(f"Parquet: {out_parquet.relative_to(REPO_ROOT)}")

    print(f"\nColumns ({combined.width}):")
    for c in combined.columns:
        print(f"  {c}: {combined[c].dtype}")


if __name__ == "__main__":
    main()
